//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Loader.Proxy.SH {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webxml.com.cn/", ConfigurationName="Proxy.SH.StockInfoWSSoap")]
    public interface StockInfoWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.com.cn/getStockInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getStockInfo(string theStockCode, string userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockInfoWSSoapChannel : Portfolio.Loader.Proxy.SH.StockInfoWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockInfoWSSoapClient : System.ServiceModel.ClientBase<Portfolio.Loader.Proxy.SH.StockInfoWSSoap>, Portfolio.Loader.Proxy.SH.StockInfoWSSoap {
        
        public StockInfoWSSoapClient() {
        }
        
        public StockInfoWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockInfoWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockInfoWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockInfoWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getStockInfo(string theStockCode, string userID) {
            return base.Channel.getStockInfo(theStockCode, userID);
        }
    }
}
