//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v6.0.2, CSLA Templates: v3.1.0.2448, CSLA Framework: v4.0.0.
//       Changes to this template will not be lost.
//
//     Template: Criteria.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
#region Using declarations

using System;

#endregion

namespace Portfolio.Business
{
    public partial class FundCriteria
    {
    }
}