//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v6.0.2, CSLA Templates: v3.1.0.2448, CSLA Framework: v4.0.0.
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'Fund.cs'.
//
//     Template: Criteria.Generated.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
#region Using declarations

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

using Portfolio.Data;
using DAL=Portfolio.Data;
using Csla.Core;
#if SILVERLIGHT
using Csla.Serialization;
#endif
using Csla.Serialization.Mobile;

#if !SILVERLIGHT
using System.Data.SqlClient;
#endif

using Csla;

#endregion

namespace Portfolio.Business
{
    [Serializable]
    public partial class FundCriteria : CriteriaBase<FundCriteria>, IGeneratedCriteria
    {
        #region Private Read-Only Members
        
        private readonly Dictionary<string, object> _bag = new Dictionary<string, object>();
        
        #endregion
        
        #region Constructors

        public FundCriteria(){}

        public FundCriteria(System.Int32 identification)
        {
            Identification = identification;
        }
        
        #endregion
        
        #region Public Properties
        
        #region Read-Write

        public System.Int32 Identification
        {
            get { return GetValue< System.Int32 >("Id"); }
            set { _bag["Id"] = value; }
        }

        public System.String FundCode
        {
            get { return GetValue< System.String >("FundCode"); }
            set { _bag["FundCode"] = value; }
        }

        public System.String FundName
        {
            get { return GetValue< System.String >("FundName"); }
            set { _bag["FundName"] = value; }
        }

        public System.String FundType
        {
            get { return GetValue< System.String >("FundType"); }
            set { _bag["FundType"] = value; }
        }

        public System.String FundCodePrefix
        {
            get { return GetValue< System.String >("FundCodePrefix"); }
            set { _bag["FundCodePrefix"] = value; }
        }

        #endregion
        
        #region Read-Only

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public Dictionary<string, object> StateBag
        {
            get
            {
                return _bag;
            }
        }

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public string TableFullName
        {
            get
            {
                return "[dbo].[Funds]";
            }
        }

        public Type EntityType
        {
            get
            {
                return typeof(DAL.Funds);
            }
        }
		
        #endregion

        #endregion

        #region Overrides
        
        public override string ToString()
        {
            var result = string.Empty;
            var cancel = false;
            
            OnToString(ref result, ref cancel);
            if(cancel && !string.IsNullOrEmpty(result))
                return result;
            
            if (_bag.Count == 0)
                return "No criterion was specified.";

            foreach (KeyValuePair<string, object> key in _bag)
            {
                result += string.Format("[{0}] = '{1}' AND ", key.Key, key.Value);
            }

            return result.Remove(result.Length - 5, 5);
        }

        #endregion

        #region Private Methods
        
        private T GetValue<T>(string name)
        {
            object value;
            if (_bag.TryGetValue(name, out value))
                return (T) value;
        
            return default(T);
        }
        
        #endregion
        
        #region Partial Methods
        
        partial void OnToString(ref string result, ref bool cancel);
        
        #endregion
        
        #region Serialization
        
        protected override void OnGetState(SerializationInfo info, StateMode mode)
        {
            base.OnGetState(info, mode);
            if (_bag.ContainsKey("Id")) info.AddValue("Id", GetValue< System.Int32 >("Id"));
            if (_bag.ContainsKey("FundCode")) info.AddValue("FundCode", GetValue< System.String >("FundCode"));
            if (_bag.ContainsKey("FundName")) info.AddValue("FundName", GetValue< System.String >("FundName"));
            if (_bag.ContainsKey("FundType")) info.AddValue("FundType", GetValue< System.String >("FundType"));
            if (_bag.ContainsKey("FundCodePrefix")) info.AddValue("FundCodePrefix", GetValue< System.String >("FundCodePrefix"));
        }

        protected override void OnSetState(SerializationInfo info, StateMode mode)
        {
            base.OnSetState(info, mode);
            if(info.Values.ContainsKey("Id")) _bag["Id"] = info.GetValue< System.Int32 >("Id");
            if(info.Values.ContainsKey("FundCode")) _bag["FundCode"] = info.GetValue< System.String >("FundCode");
            if(info.Values.ContainsKey("FundName")) _bag["FundName"] = info.GetValue< System.String >("FundName");
            if(info.Values.ContainsKey("FundType")) _bag["FundType"] = info.GetValue< System.String >("FundType");
            if(info.Values.ContainsKey("FundCodePrefix")) _bag["FundCodePrefix"] = info.GetValue< System.String >("FundCodePrefix");
        }

        #endregion
    }
}