//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PortfolioMVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PortfolioEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PortfolioEntities object using the connection string found in the 'PortfolioEntities' section of the application configuration file.
        /// </summary>
        public PortfolioEntities() : base("name=PortfolioEntities", "PortfolioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PortfolioEntities object.
        /// </summary>
        public PortfolioEntities(string connectionString) : base(connectionString, "PortfolioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PortfolioEntities object.
        /// </summary>
        public PortfolioEntities(EntityConnection connection) : base(connection, "PortfolioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Fund> Funds
        {
            get
            {
                if ((_Funds == null))
                {
                    _Funds = base.CreateObjectSet<Fund>("Funds");
                }
                return _Funds;
            }
        }
        private ObjectSet<Fund> _Funds;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Funds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFunds(Fund fund)
        {
            base.AddObject("Funds", fund);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortfolioModel", Name="Fund")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Fund : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Fund object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fundCode">Initial value of the FundCode property.</param>
        /// <param name="fundType">Initial value of the FundType property.</param>
        public static Fund CreateFund(global::System.Int32 id, global::System.String fundCode, global::System.String fundType)
        {
            Fund fund = new Fund();
            fund.Id = id;
            fund.FundCode = fundCode;
            fund.FundType = fundType;
            return fund;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FundCode
        {
            get
            {
                return _FundCode;
            }
            set
            {
                OnFundCodeChanging(value);
                ReportPropertyChanging("FundCode");
                _FundCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FundCode");
                OnFundCodeChanged();
            }
        }
        private global::System.String _FundCode;
        partial void OnFundCodeChanging(global::System.String value);
        partial void OnFundCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FundName
        {
            get
            {
                return _FundName;
            }
            set
            {
                OnFundNameChanging(value);
                ReportPropertyChanging("FundName");
                _FundName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FundName");
                OnFundNameChanged();
            }
        }
        private global::System.String _FundName;
        partial void OnFundNameChanging(global::System.String value);
        partial void OnFundNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FundType
        {
            get
            {
                return _FundType;
            }
            set
            {
                OnFundTypeChanging(value);
                ReportPropertyChanging("FundType");
                _FundType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FundType");
                OnFundTypeChanged();
            }
        }
        private global::System.String _FundType;
        partial void OnFundTypeChanging(global::System.String value);
        partial void OnFundTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FundCodePrefix
        {
            get
            {
                return _FundCodePrefix;
            }
            set
            {
                OnFundCodePrefixChanging(value);
                ReportPropertyChanging("FundCodePrefix");
                _FundCodePrefix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FundCodePrefix");
                OnFundCodePrefixChanged();
            }
        }
        private global::System.String _FundCodePrefix;
        partial void OnFundCodePrefixChanging(global::System.String value);
        partial void OnFundCodePrefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();

        #endregion
    
    }

    #endregion
    
}
